### ISSUE TITLE
Support Audio File Inputs as Documents

### ISSUE THREAD

**Issue by shreyashankar** [ucbepic/docetl#11]
We need to add support for audio file inputs as documents in our pipeline system. This will allow users to process audio files (e.g., MP3) and automatically transcribe them using services like OpenAI's Whisper API.

## Current Situation
Currently, our system supports text-based documents and JSON files as inputs. We need to extend this functionality to include audio files.

## Proposed Solutions

1. Augment Dataset Types:
   - Add a new dataset type called "audio" or "speech"
   - Example:
     ```yaml
     datasets:
       debate_audio:
         type: audio
         path: "/path/to/audio/files/*.mp3"
         transcription_service: whisper  # Optional, default to Whisper
     ```

2. JSON Object with Audio Keys:
   - For JSON datasets, introduce a convention where keys prefixed with `_audio` are treated as paths to audio files
   - Example:
     ```yaml
     datasets:
       mixed_data:
         type: file
         path: "/path/to/mixed_data.json"
     ```
     Where the JSON file might contain:
     ```json
     {
       "title": "Presidential Debate 2023",
       "date": "2023-10-15",
       "_audio": "/path/to/debate_audio.mp3"
     }
     ```

3. Audio Transcription Operation:
   - Add a new operation type for audio transcription
   - Example:
     ```yaml
     operations:
       - name: transcribe_audio
         type: transcribe
         input_key: audio_path
         output_key: transcript
         service: whisper
     ```

## Implementation Details

1. Add audio file detection and handling in the dataset loading process
2. Implement audio transcription functionality, potentially using OpenAI's Whisper API
3. Update the pipeline execution engine to handle audio files and transcription
4. Modify relevant schema definitions to include audio-related fields
5. Update documentation to reflect new audio input capabilities
