### ISSUE TITLE
add `enum` type for LLM output types

### ISSUE THREAD

**Issue by shreyashankar** [ucbepic/docetl#201]
Users want to be able to add enum type outputs for operations. For example, a multi class classifer.

The interface can look something like

```yaml
output:
  schema:
    insights: "list[{insight: string, confidence: number}]"
    metadata: "{timestamp: string, source: string}"
    status: "enum[pending,in_progress,completed]"
```

We'd have to figure out how to convert it to openapi-compatible schemas (relevant info might be [here](https://platform.openai.com/docs/guides/function-calling#use-enums-for-function-arguments-when-possible)), and include this logic in the `convert_val` function [here](https://github.com/ucbepic/docetl/blob/329d47f2c9566f3045b8a13f7a65bd53b3ab63bf/docetl/operations/utils/validation.py#L77) so the LLM reads the enum correctly. The `convert_val` function is used when creating the LLM call for an operation ([here](https://github.com/ucbepic/docetl/blob/329d47f2c9566f3045b8a13f7a65bd53b3ab63bf/docetl/operations/utils/api.py#L392)).

The PR should also add a test for a map operation with an output schema with an enum type.

We'd also have to modify the front-end to support enum types, but we can do that in a separate issue and PR.
