### ISSUE TITLE
How to stack multiple individual "process" operations to perform sequential processing?

### ISSUE THREAD

**Issue by jacklanda** [ucbepic/docetl#55]
For example, I would like to conduct the following processes to handle my pipeline:

**Step 0. Chunk textual data into many partitions within one-call LLM --> ?**
Step 1. Map partitioned data splits into one process procedure which is defined by my prompt --> a naive `map` ops.
Step 2. Unnest ...
Step 3. Reduce by a specific key of each processed item.

How could I perform chunking handling before the later operations?

**Comment by shreyashankar** [comment]
Great question! It is a common pattern and deserves some documentation, so I added this example: https://ucbepic.github.io/docetl/examples/split-gather/

At a high level, we have two (non-LLM) operations that can aid in chunking: `split` and `gather`. The `split` operator chunks up data into equal-sized units (we also have the option to split on a delimiter); nothing more. The `gather` operator is optional and augments each chunk with context from "peripheral" chunks. For example, you can support an overlap of half a chunk size by specifying a gather peripheral configuration like this:

```yaml
peripheral_chunks:
  previous:
    tail:
      count: 0.5
  next:
    head:
      count: 0.5
```

You can also have the first chunk of the document be peripheral context for _all_ chunks:

```yaml
peripheral_chunks:
  previous:
    head:
      count: 1 # this keeps the first chunk included as context in addition to the half-chunk before and after, when processing each individual chunk
    tail:
      count: 0.5
  next:
    head:
      count: 0.5
```

Check out the docs for split and gather:
- split: https://ucbepic.github.io/docetl/operators/split/
- gather: https://ucbepic.github.io/docetl/operators/gather/

LMK further questions you have, and feel free to reach out via discord too! Discord link in this repo's readme :-)
